### ISSUE TITLE
Allow linking to static libraries

### ISSUE THREAD

**Issue by ianmackenzie** [dimi309/conan-glew#2]
At least on Windows, both glew32.lib (dynamic linking) and libglew32.lib (static linking) are included but only glew32.lib is ever added to the generated .props file. Could a glew:shared option be added that when set to false would cause linking against libglew32.lib instead?

**Comment by dimi309** [comment]
Hi Ian,

The short answer is yes! 😄 When I set this package up, I used glew's CMakeLists.txt file for all systems, including Windows. However, when building with cmake on Windows, even libglew32.lib makes projects that use it look for the glew dll. I came across some forum post or documentation at the time (I've lost the link 😦 ) which said that dynamic builds will be supported by the cmakelists file in glew version 2 or something like that. So I left the conan package without the shared option. But now I've figured out how to set up conan packages that are built using the VS solution, so I can fix this version even before packaging version 2. I'll be doing that VERY soon & I'll let you know.

**Comment by ianmackenzie** [comment]
Thanks, sounds great! I'm just glad the question at least made sense, I'm pretty new to using Conan so I was worried I was just totally misunderstanding something =)

**Comment by dimi309** [comment]
Nope! You got it! 👍 
(But I hear you. I keep misunderstanding everything about everything myself all the time. That's why we have bug reports, discussion boards and pull requests :laughing: )

**Comment by dimi309** [comment]
Hi Ian,

I've got some GLEW packages ready for static linking:

https://www.conan.io/source/glew/1.13.0/coding3d/testing

Let me know if they work for you. Don't forget to **link to the OpenGL32.lib library** when using the statically linked glew library. I suppose you would probably know this already, but it's a detail that has given me a lot of grief, so I thought to mention it. :smile:

Once I've made sure that everything is in order I will add these packages to the "stable" set.

**Comment by ianmackenzie** [comment]
Hmm, I'm getting some failures:

```
glew/1.13.0@coding3d/testing: Installing package 63da998e3642b50bee33f4449826b2d623661505
glew/1.13.0@coding3d/testing: Looking for package 63da998e3642b50bee33f4449826b2d623661505 in remote 'conan.io'
glew/1.13.0@coding3d/testing: WARN: Binary for 63da998e3642b50bee33f4449826b2d623661505 not in remote: Package not found!
ERROR: Can't find a 'glew/1.13.0@coding3d/testing' package for the specified options and settings

- Try to build from sources with "--build glew" parameter
- If it fails, you could try to contact the package author  at 'http://github.com/dimi309/conan-glew', report your configuration and try to collaborate to support it.

Package configuration:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=14, os=Windows
- Options: shared=False
```

I note that `63da998e3642b50bee33f4449826b2d623661505` is the ID of the `stable` version of the package, so it's suspicious that it's showing up here. I originally thought Conan was getting confused so I got rid of my .conan directory before running Conan again, but got the same error. Is it possible you didn't update an ID somewhere, or is this a Conan issue?

**Comment by dimi309** [comment]
Firstly, I have to tell you that I made some more changes after I wrote and uploaded a configuration that pre-compiles the shared version by default. So the /testing version you see, is actually a shared one, because I did not know that the static version would just go away (I thought I would add to the existing set of packages).

I am not sure but I think that conan tries the stable version because it doesn't find what you are looking for in /testing, but I am just making an assumption. The important thing is that the recipe that CAN build a static version is there (in /testing). Try to build from sources as it says by executing the following before building your project, from within the directory where your conanfile is:

`conan install --build glew`

It will build the version your project is looking for and install it in your local cache. Let me know how it went (and don't forget to link to OpenGL32.lib :) )

**Comment by dimi309** [comment]
I've made some more improvements and the precompiled static library has been deployed to conan. I have tested it with a large application here and it's doing fine :)

Whenever you have some time, maybe you can delete your downloaded versions and try it out. Apart from erasing them from the data directory you can execute:

`conan search`

and then:

`conan remove [copy paste full signature of package here]`

Instead of linking explicitly with the OpenGL32.lib library, which I keep mentioning, you can use conan facilities to perform this and other configuration details. For example, with CMake, this is what I am doing in the little test project of GLEW:

https://github.com/dimi309/conan-glew/blob/develop/test/CMakeLists.txt

Looking forward to any feedback! If all goes well, I can merge this with the stable version.

**Comment by dimi309** [comment]
We also have GLEW 2.0.0 now: https://www.conan.io/source/glew/2.0.0/coding3d/testing 😎

**Comment by ianmackenzie** [comment]
Wow, quick work! I can't get things working here at work (various issues with proxies and Visual Studio versions) so I'll have to take a crack sometime this weekend at home. But I'm going to assume this is resolved now =) Thanks for all the responses!

**Comment by dimi309** [comment]
You're welcome! Thanks for trying out the package and don't hesitate to write for any other questions / comments / bugs.
